Disable autotools/gtkmm test in CI
Disable the autotools/gtkmm test in CI, by not installing it's
prerequisites.

This fails with:

/usr/include/glibmm-2.4/glibmm/threads.h:660:29: error: cannot convert 'GPrivate' {aka '_GPrivate'} to 'GPrivate*' {aka '_GPrivate*'} in return

which is a bug in upsteam gtkmm, exposed by updated gcc

See also https://bugzilla.redhat.com/show_bug.cgi?id=1540795